[DEFAULT]
spark_app_name = size-calculation-job
spark_master = local[*]
input_path = input/
input_format = parquet
output_path = output/
output_format = parquet
output_mode = overwrite
batch_size = 10000
metrics_enabled = true